### ISSUE TITLE
Change command to `mkdir -p` to assure that all subdirectories will be made

### ISSUE THREAD

**Issue by fedebenelli** [Diegoolei/Fortran77-Cloud-Model#1]
When making the output directory in:
https://github.com/Diegoolei/Fortran77-Cloud-Model/blob/f77-to-f90/src/config.f90#L15-L17

If intermediate directories don't exist, like for example `this/will/be/my/output_dir` that command without the `--parent` flag will fail. 

On a side note, I'm not sure if that will work on Windows (though is outside of scope/consideration for now)

**Comment by leliel12** [comment]
https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2023-1/makedirqq.html <<< mkdir portable

**Comment by fedebenelli** [comment]
No es portable, solo funciona con `ifort` e `ifx` de intel.

`fpm` usa esto: https://fortran-lang.github.io/fpm/proc/mkdir.html

**Comment by Diegoolei** [comment]
Solved with magic (Python)
