### ISSUE TITLE
It is not Fortran 77 or Fortran 90

### ISSUE THREAD

**Issue by Beliavsky** [Diegoolei/Fortran77-Cloud-Model#7]
Since your Fortran code uses constructs such as `do concurrent`, it is not Fortran 90 but is at least Fortran 2008 https://www.ibm.com/docs/en/xl-fortran-linux/16.1.1?topic=attributes-do-concurrent-fortran-2008 . I suggest renaming the project to Fortran-Cloud-Model and to avoid saying it is Fortran 90 in the Readme. You could just say it is Modern Fortran.

**Comment by Diegoolei** [comment]
Changed!
